<?php

/** @noinspection PhpMultipleClassDeclarationsInspection */

declare(strict_types=1);

namespace Resursbank\EcomTest\Integration\Module\PaymentMethod\Api;

use JsonException;
use PHPUnit\Framework\TestCase;
use Resursbank\Ecom\Config;
use Resursbank\Ecom\Exception\ApiException;
use Resursbank\Ecom\Exception\CacheException;
use Resursbank\Ecom\Exception\TestException;
use Resursbank\Ecom\Exception\Validation\EmptyValueException;
use Resursbank\Ecom\Lib\Api\Credentials;
use Resursbank\Ecom\Lib\Cache\CacheInterface;
use Resursbank\Ecom\Lib\Cache\None;
use Resursbank\Ecom\Lib\Log\FileLogger;
use Resursbank\Ecom\Lib\Log\LoggerInterface;
use Resursbank\Ecom\Lib\Network\Model\Auth\Jwt;
use Resursbank\Ecom\Module\PaymentMethod\Api\GetStores as Api;
use Resursbank\Ecom\Module\PaymentMethod\Api\GetPaymentMethods\Request;
use Resursbank\Ecom\Module\PaymentMethod\Api\GetPaymentMethods\Response;
use Resursbank\Ecom\Module\PaymentMethod\Model\Store;
use Resursbank\Ecom\Module\PaymentMethod\Repository;
use Resursbank\EcomTest\Data\ApiResponse\GetStores;
use stdClass;
use function is_array;
use function json_encode;

/**
 * Test business logic of payment methods Repository class.
 *
 * @psalm-suppress PropertyNotSetInConstructor
 * @SuppressWarnings(PHPMD.TooManyPublicMethods)
 * @SuppressWarnings(PHPMD.TooManyMethods)
 * @todo We cannot test that readCache() converts ReflectionException because we cannot mock DataConverter.
 */
class GetPaymentMethodsTest extends TestCase
{
    private Api $api;

    public function setUp(): void
    {
        Config::setup(
            logger: $this->createMock(originalClassName: LoggerInterface::class),
            cache: $this->createMock(originalClassName: CacheInterface::class),
            jwtAuth: new Jwt(
                clientId: $_ENV['JWT_AUTH_CLIENT_ID'],
                clientSecret: $_ENV['JWT_AUTH_CLIENT_SECRET'],
                scope: $_ENV['JWT_AUTH_SCOPE'],
                grantType: $_ENV['JWT_AUTH_GRANT_TYPE']
            )
        );

        $this->api = new Api();

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testExecThrowsOnEmptyRoute(): void
    {
        $this->expectException(EmptyValueException::class);
        $this->api->exec(store: '');
    }

    public function testExecReturnsArray(): void
    {
        $this->assertIsArray($this->api->exec(store: $_ENV['RESURS_API_STORE']));
    }
}
