<?php

/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var Html $this */
/** @psalm-scope-this \Resursbank\Ecom\Module\Widget\Loader\Html */

use Resursbank\Ecom\Lib\Locale\Translator;
use Resursbank\Ecom\Module\Widget\Loader\Html;

?>

<?php // AJAX loading animation. ?>
<div class="rb-loader-spinner-container" style="display: <?= $this->display ? 'block' : 'none' ?>;">
    <div class="rb-loader-spinner">
        <svg class="rb-loader-circular" viewBox="25 25 50 50">
            <circle class="rb-loader-path" cx="50" cy="50" r="20" fill="none" stroke-width="5" stroke-miterlimit="10"/>
        </svg>
    </div>
</div>

<?php // Loader content overlay. ?>
<div class="rb-loader-overlay" style="display: <?= $this->display ? 'block' : 'none' ?>;"></div>
