<?php

/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var Info $this */

use Resursbank\Ecom\Module\Debug\Widget\Info;

?>

<style>
  .rb-debug-info {
    border-collapse: collapse;
    font-family: Arial, Helvetica, sans-serif;
    display: flex;
    flex-direction: column;
    row-gap: 30px;
  }

  .rb-debug-info,
  .rb-debug-info * {
    box-sizing: border-box;
  }

  .rb-debug-info th {
    text-align: left;
    padding: 15px 10px;
    font-weight: 600;
  }

  .rb-debug-info td {
    padding: 15px 10px;
  }

  .rb-debug-info table {
    border-collapse: collapse;
  }

  .rb-debug-info thead {
    background-color: #dddddd;
    color: rgb(46, 46, 46);
    border: 1px solid rgb(192, 192, 192);
  }

  .rb-debug-info tbody {
    color: white;
    border: 1px solid #006464;
  }

  .rb-debug-info tbody tr:last-child {
    border-bottom: 1px solid #009b91;
  }

  .rb-debug-info tbody tr:nth-child(even) {
    background-color: #006464;
  }

  .rb-debug-info tbody tr:nth-child(odd) {
    background-color: #009b91;
  }

  .rb-debug-info-warning td {
    font-family: Arial, Helvetica, sans-serif;
    border: 1px solid #9c7d05;
    border-top: 0;
    background: #f5dd7f;
    color: #242424;
    padding: 15px;
    border-bottom: 0;
  }

  .rb-debug-info-warning td:first-child {
    border-right: 0;
  }

  .rb-debug-info-warning td:last-child {
    border-left: 0;
  }

  .rb-debug-info table tbody .rb-debug-info-warning:last-child td {
    border-bottom: 1px solid #9c7d05;
  }
</style>

<div class="rb-debug-info">
  <table>
    <thead>
      <tr>
        <th colspan="2">Debug Information</th>
      </tr>
    </thead>
    <tbody>
      <?php if ($this->pluginVersion !== ''): ?>
      <tr>
        <td><?= $this->translate(id: 'plugin-version') ?></td>
        <td><?= $this->pluginVersion ?></td>
      </tr>
      <?php endif; ?>
      <tr>
        <td><?= $this->translate(id: 'ecom-version') ?></td>
        <td><?= $this->getEcomVersion() ?>></td>
      </tr>
      <tr>
        <td><?= $this->translate(id: 'php-version') ?></td>
        <td>8.1.15</td>
      </tr>
      <tr>
        <td><?= $this->translate(id: 'php-curl') ?></td>
        <td>1.15.5</td>
      </tr>
      <tr class="rb-debug-info-warning">
        <td><?= $this->translate(id: 'php-openssl') ?></td>
        <td>Missing</td>
      </tr>
      <tr>
        <td><?= $this->translate(id: 'server-ip') ?></td>
        <td>192.168.1.105</td>
      </tr>
      <tr>
        <td><?= $this->translate(id: 'callback-url') ?></td>
        <td>192.168.1.105</td>
      </tr>
    </tbody>
  </table>
</div>
