<?php

/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var PartPayment $this */
/** @psalm-scope-this \Resursbank\Ecom\Module\PaymentMethod\Widget\PartPayment */

use Resursbank\Ecom\Module\PaymentMethod\Widget\PartPayment;

?>

<?php if ($this->iframeUrl !== ''): ?>
        async function getStartingAtCost(amount) {
            let url ='<?= $this->apiUrl ?>&amount=' + amount.toString();

            let response = await fetch(url, {
                method: 'GET',
                headers: {
                    "Content-Type": "application/json"
                }
            });
            return await response.json();
        };
<?php endif; ?>
