<?php

/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var PartPayment $this */

use Resursbank\Ecom\Module\PaymentMethod\Widget\PartPayment;

?>

<?php

if ($this->iframeUrl !== '') : ?>
  <div class="rb-pp">
    <!-- Logo -->
    <div id="rb-pp-logo-container"><?= $this->logo ?></div>
      <?php

if ($this->displayInfoText) : ?>
        <!-- Pay in installments -->
        <div id="rb-pp-info"><p><?= $this->infoText ?></p></div>
      <?php endif; ?>
    <!-- Example line here -->
    <div id="rb-pp-example"><p><?= $this->startingAt ?></p></div>
    <!-- Error message -->
    <div id="rb-pp-error" class="rb-pp-hidden" style="display:none;"><p class="rb-pp-error"><?= $this->error ?></p>
    </div>
    <!-- Read More link -->
    <div id="rb-pp-readmore">
      <p>
        <a onClick="document.getElementById('rb-pp-hidden').style.display='block';" href="#"><?= $this->readMore ?></a>
      </p>
    </div>
    <div id="rb-pp-hidden" style="display:none;">
      <div id="rb-pp-background" onclick="document.getElementById('rb-pp-hidden').style.display='none';"></div>
      <div id="rb-pp-iframe-container">
        <!--
          Note that this X-close solution has been implemented to simplify the ability to close the payment info widget
          when it is opened modally. The side view might be affected so that there is a lot of empty space on the sides
          of it, but this compensates for the issues with the touch area not moving based on the screen resolution used.
          -->
        <div id="x-button"
             style="cursor: pointer; position: absolute; top: 0px; right: 0px; font-size: 24px; z-index: 10; background-color: white; padding: 5px;"
             onclick="document.getElementById('rb-pp-hidden').style.display='none';">X
        </div>
        <iframe id="rb-pp-iframe" src="<?= $this->iframeUrl ?>" loading="eager"></iframe>
      </div>
    </div>
  </div>
<?php endif; ?>
