<?php

/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

/** @psalm-scope-this Resursbank\Ecom\Module\PaymentMethod\Widget\PaymentMethods */

declare(strict_types=1);

/** @var PaymentMethods $this */

use Resursbank\Ecom\Module\PaymentMethod\Models\PaymentMethod;
use Resursbank\Ecom\Module\PaymentMethod\Widget\PaymentMethods;

/** @var PaymentMethod[] $paymentMethods */
$paymentMethods = $this->paymentMethods->toArray();
?>

<?php if (count($paymentMethods) !== 0) : ?>
    <style>
        .rb-payment-methods {
            border-collapse: collapse;
            font-family: Arial, Helvetica, sans-serif;
            display: flex;
            flex-direction: column;
            row-gap: 30px;
        }

        .rb-payment-methods,
        .rb-payment-methods * {
            box-sizing: border-box;
        }

        .rb-payment-methods th {
            text-align: left;
            padding: 15px 10px;
            font-weight: 600;
        }

        .rb-payment-methods td {
            padding: 15px 10px;
        }

        .rb-payment-methods table {
            border-collapse: collapse;
        }

        .rb-payment-methods thead {
            background-color: #dddddd;
            color: rgb(46, 46, 46);
            border: 1px solid rgb(192, 192, 192);
        }

        .rb-payment-methods tbody {
            color: white;
            border: 1px solid #006464;
        }

        .rb-payment-methods tbody tr:last-child {
            border-bottom: 1px solid #009b91;
        }

        .rb-payment-methods tbody tr:nth-child(even) {
            background-color: #006464;
        }

        .rb-payment-methods tbody tr:nth-child(odd) {
            background-color: #009b91;
        }
    </style>
    <div class="rb-payment-methods">
        <table>
            <thead>
            <tr>
                <th><?= $this->nameLabel ?></th>
                <th><?= $this->minTotalLabel ?></th>
                <th><?= $this->maxTotalLabel ?></th>
                <th><?= $this->sortOrderLabel ?></th>
            </tr>
            </thead>
            <tbody>
                <?php foreach ($paymentMethods as $key => $method) : ?>
                    <tr>
                        <td><?= $method->name ?></td>
                        <td><?= $method->minPurchaseLimit ?></td>
                        <td><?= $method->maxPurchaseLimit ?></td>
                        <td><?= $key + 1 ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif; ?>