<?php

/** @noinspection PhpUnhandledExceptionInspection */

/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var Log $this */

use Resursbank\Ecom\Module\PaymentHistory\Translator;
use Resursbank\Ecom\Module\PaymentHistory\Widget\Log;

?>
<script>
    function showExtra(data) {
        document.getElementById('rb-ph-extra-content').innerHTML = data;
        document.getElementById('rb-ph-log-table').style.display = 'none';
        document.getElementById('rb-ph-extra').style.display = 'block';
    }

    function showLogTable() {
        document.getElementById('rb-ph-extra').style.display = 'none';
        document.getElementById('rb-ph-log-table').style.display = '';
    }

    function showWidget() {
        document.getElementById('rb-ph-hidden').style.display='block';
    }

    function hideWidget() {
        document.getElementById('rb-ph-hidden').style.display='none';
    }
</script>
<div id="rb-ph">
  <div id="rb-ph-button">
    <p>
      <a onclick="showWidget();" href="#" class="btn-link">
        <?= Translator::translate(phraseId: 'link-title') ?>
      </a>
    </p>
  </div>
  <div id="rb-ph-hidden" style="display:none;">
    <div id="rb-ph-background" onclick="hideWidget();"></div>
    <div id="rb-ph-content-container">
      <div id="rb-ph-payment-id">
        <?= $this->getWidgetTitle() ?>
        <div onclick="hideWidget();" class="close-window-link">
            <div class="close-symbol">x</div>
        </div>
      </div>
      <div id="rb-ph-log">
        <div id="rb-ph-extra" style="display: none;">
          <div id="rb-ph-go-back">
            <a onclick="showLogTable();" href="#" class="btn-link">
              <?= Translator::translate(phraseId: 'go-back') ?>
            </a>
          </div>
          <div id="rb-ph-extra-content"></div>
        </div>
        <table id="rb-ph-log-table">
          <thead>
            <tr>
              <th><?= Translator::translate(phraseId: 'time') ?></th>
              <th><?= Translator::translate(phraseId: 'event') ?></th>
              <th><?= Translator::translate(phraseId: 'user') ?></th>
              <th><?= Translator::translate(phraseId: 'previous-status') ?></th>
              <th><?= Translator::translate(phraseId: 'current-status') ?></th>
              <th><?= Translator::translate(phraseId: 'extra') ?></th>
              <th><?= Translator::translate(phraseId: 'result') ?></th>
            </tr>
          </thead>
          <tbody>
          <?php

foreach ($this->entries as $entry) : ?>
            <tr class="<?= $this->getResultClass(entry: $entry) ?>">
              <td><?= date(
	format: 'Y-m-d H:i:s',
	timestamp: $entry->time
) ?></td>
              <td><?= Translator::translate(
	phraseId: $entry->event->value
) ?></td>
              <td><?= $this->getUser(entry: $entry) ?></td>
              <td><?= $entry->previousOrderStatus ?></td>
              <td><?= $entry->currentOrderStatus ?></td>
              <td>
                <?php

if ($this->showExtraBtn(entry: $entry)) : ?>
                <p class="rb-rh-show-extra-btn">
                  <a onclick="showExtra('<?= $this->getExtraData(
	entry: $entry
) ?>');" href="#">
                      <?= Translator::translate(phraseId: 'show-extra') ?>
                  </a>
                </p>
                <?php elseif ($entry->extra !== null) : ?>
                    <?= $entry->extra ?>
                <?php endif; ?>
              </td>
              <td class="rb-ph-result-icon"></td>
            </tr>
          <?php endforeach;

 ?>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
