<?php

/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var DurationBymonths $this */
/** @psalm-scope-this \Resursbank\Ecom\Module\AnnuityFactor\Widget\DurationByMonths */

use Resursbank\Ecom\Module\AnnuityFactor\Widget\DurationBymonths;

?>

<?php if ($this->endpointUrl !== null): ?>
    async function rbGetDurationsForPaymentMethodId(paymentMethodId) {
        let url ='<?= $this->endpointUrl ?>';

        let result;
        await fetch(url, {
            method: 'POST',
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify({ paymentMethodId })
        })
        .then(response => response.json())
        .then(response => result = { status: 'success', response})
        .catch(error => result = { status: 'error', error});

        return result;
    };
<?php endif; ?>
