<?php

/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var DurationBymonths $this */
/** @psalm-scope-this \Resursbank\Ecom\Module\AnnuityFactor\Widget\DurationByMonths */

use Resursbank\Ecom\Module\AnnuityFactor\Widget\DurationBymonths;

?>

<?php if ($this->endpointUrl !== null): ?>
  async function getStartingAtCost(paymentMethodId) {
    let url ='<?= $this->endpointUrl ?><?= $this->separator ?>paymentMethodId=' + paymentMethodId;

    let response = await fetch(url, {
      method: 'GET',
      headers: {
        "Content-Type": "application/json"
      }
    });
    return await response.json().then(resp => {
      return resp.options;
    }).catch(function() {
      return {};
    });
  };
<?php endif; ?>
