<?php

/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var CostList $this */

use Resursbank\Ecom\Lib\Locale\Translator;
use Resursbank\Ecom\Lib\Model\PriceSignage\Cost;
use Resursbank\Ecom\Lib\Utilities\Price;
use Resursbank\Ecom\Module\PriceSignage\Widget\CostList;

?>

<div class="rb-ps-cl expanded" data-payment-method="<?= $this->method->id ?>">
    <?php /** @var Cost $cost */ ?>
    <div class="rb-ps-cl-expander">
        <div class="rb-ps-cl-expander-icon">
            &raquo;
        </div>
    </div>
    <div class="rb-ps-cl-content">
        <?php foreach ($this->priceSignage->costList as $cost): ?>
            <div class="rb-ps-cl-section">
                <div class="rb-ps-cl-row rb-ps-cl-title">
                    <p><?= $this->getDuration(cost: $cost) ?></</p>
                    <p><?= Price::format(value: $cost->monthlyCost) ?> / <?= Translator::translate('per-month-cost') ?></p>
                </div>
                <div class="rb-ps-cl-row rb-ps-cl-info">
                    <p><?= $this->getSetupFee(cost: $cost) ?></p>
                    <p><?= $this->getAdministrationFee(cost: $cost) ?></p>
                </div>
                <div class="rb-ps-cl-row rb-ps-cl-info">
                    <p><?= Translator::translate(phraseId: 'interest') ?> <?= $cost->interest ?>%</p>
                    <p><?= Translator::translate(phraseId: 'effective-interest') ?> <?= $cost->effectiveInterest ?>%</p>
                    <p><?= Translator::translate(phraseId: 'total') ?> <?= Price::format(value: $cost->totalCost) ?></p>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
