<?php

/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Resursbank\Ecom\Lib\Locale\Translator;

?>

<div class="rb-si">
  <dl>
    <?php if ($this->pluginVersion): ?>
    <dt><?= Translator::translate(phraseId: 'plugin-version') ?></dt>
    <dd><?= $this->pluginVersion ?></dd>
    <?php endif; ?>
    <dt><?= Translator::translate(phraseId: 'php-version') ?></dt>
    <dd><?= $this->getPhpVersion() ?></dd>
    <?php if ($this->getEcomVersion()): ?>
    <dt><?= Translator::translate(phraseId: 'ecom-version') ?></dt>
    <dd><?= $this->getEcomVersion() ?></dd>
    <?php endif; ?>
  </dl>
</div>
