<?php

/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var Html $this */

use Resursbank\Ecom\Config;
use Resursbank\Ecom\Lib\Locale\Translator;
use Resursbank\Ecom\Lib\Model\PaymentMethod;
use Resursbank\Ecom\Lib\Utilities\Price;
use Resursbank\Ecom\Module\UserSettings\Repository;
use Resursbank\Ecom\Module\Widget\PaymentMethod\Html;

?>

<?php

if (count($this->paymentMethods) !== 0) : ?>
  <div class="rb-payment-methods">
    <table>
      <thead>
      <tr>
        <th>
            <?= htmlspecialchars(
                string: Translator::translate(phraseId: 'name')
            ) ?>
        </th>
        <th>
            <?= Translator::translate(phraseId: 'min-total') ?>
        </th>
        <th>
            <?= Translator::translate(phraseId: 'max-total') ?>
        </th>
        <th>
            <?= Translator::translate(phraseId: 'customer-type') ?>
        </th>
        <th>
            <?= Translator::translate(phraseId: 'sort-order') ?>
        </th>
      </tr>
      </thead>
      <tbody>
      <?php /** @var PaymentMethod $method */ ?>
      <?php

foreach ($this->paymentMethods as $method) : ?>
        <tr id="rb-pm-<?= $method->getId() ?>">
          <td><?= htmlspecialchars(string: $method->getName()) ?></td>
          <td><?= Price::format(value: $method->getMinLimit())?></td>
          <td><?= Price::format(value: $method->getMaxLimit()) ?></td>
          <td><?= htmlspecialchars(string: $this->getCustomerTypes(method: $method)) ?></td>
          <td><?= $method->getSortOrder() ?></td>
        </tr>
<?php endforeach; ?>
      </tbody>
    </table>
  </div>
<?php else : ?>
  <p class="rb-payment-methods-warning">
      <?= Translator::translate(phraseId: 'no-payment-methods') ?>
  </p>
  <?php if (!Repository::hasUserCredentials()) : ?>
    <p class="rb-payment-methods-warning">
        <?= Translator::translate(phraseId: 'configure-credentials') ?>
    </p>
  <?php elseif (Config::getStoreId() === '') : ?>
    <p class="rb-payment-methods-warning">
        <?= Translator::translate(phraseId: 'configure-store') ?>
    </p>
  <?php endif; ?>
<?php endif; ?>
