<?php
/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Resursbank\Ecom\Lib\Locale\Translator;
use Resursbank\Ecom\Lib\Log\LogLevel;

/** @var Resursbank\Ecom\Module\Widget\CacheManagement\Js $this */
?>

class Resursbank_CacheManagement {
    'use strict';

    /**
     * Safely override pre-defined functions and properties using the supplied
     * overrides parameter.
     *
     * @param {{}} overrides
     */
    constructor(
        overrides = {}
    ) {
        for (const [key, value] of Object.entries(overrides)) {
            if (typeof this[key] === typeof value) {
                this[key] = value;
            } else {
                console.warn('Failed to overwrite ' + key + ', type mismatch.');
            }
        }
    }

    /**
     * Whether an AJAX request is active.
     *
     * @type {boolean}
     */
    fetching = false;

    /**
     * Setup event listeners for button click.
     *
     * @returns {void}
     */
    setupEventListeners() {
        var that = this;

        try {
            this.getButtonElement().addEventListener('click', function (e) {
                e.preventDefault();
                that.clearCache();
            });
        } catch (e) {
            <?php if (LogLevel::isDebugMode()): ?>
            console.warn(e);
            <?php endif; ?>
        }
    }

    /**
     * Perform AJAX request to clear cache.
     */
    clearCache() {
        try {
            if (this.fetching) {
                return;
            }

            this.toggleFetch(true);

            const url = this.getUrl();

            if (url === '') {
                throw new Error('<?= Translator::translate(phraseId: 'cache-clear-missing-url') ?>');
            }

            fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                }
            })
                .then(this.handleFetchResponse.bind(this))
                .then(this.handleFetchData.bind(this))
                .then(() => {
                    this.toggleFetch(false)
                })
                .then(this.onComplete.bind(this))
                .catch(this.errorHandler.bind(this));
        } catch (e) {
            this.errorHandler(e);
        }
    }

    /**
     * Resolve URL for AJAX request.
     *
     * @returns {string}
     */
    getUrl() {
        return '<?= $this->url ?>';
    }

    /**
     * Get button element.
     *
     * @returns {HTMLButtonElement}
     */
    getButtonElement() {
        let result = document.getElementById('resursbank-cache-clear-button');

        if (!(result instanceof HTMLButtonElement)) {
            throw new Error('<?= Translator::translate(phraseId: 'cache-clear-missing-button') ?>');
        }

        return result;
    }

    /**
     * Disable / enable AJAX request. We will also reflect the state to the
     * button element and show a spinner icon indicating an AJAX request is ongoing.
     *
     * @param {boolean} state
     */
    toggleFetch(state) {
        this.onToggle(state);
        this.fetching = Boolean(state);

        const button = this.getButtonElement();

        if (this.fetching) {
            button.setAttribute('disabled', '');
            button.classList.add('loading');
        } else {
            button.removeAttribute('disabled');
            button.classList.remove('loading');
        }
    }

    /**
     * Resolve JSON data from request response.
     *
     * @param {Response} response
     * @returns {Promise<any>|undefined}
     */
    handleFetchResponse(response) {
        if (!response.ok) {
            throw new Error(
                '<?= Translator::translate(phraseId: 'cache-clear-server-error') ?>'
            );
        } else {
            return response.json();
        }
    };

    /**
     * Handle response from AJAX request (throw error or show success).
     *
     * @param {any} data
     */
    handleFetchData(data) {
        if (typeof data === 'undefined') {
            return;
        }

        if (data.error) {
            throw new Error(data.error);
        } else {
            this.onSuccess(data);
        }
    }

    /**
     * Basic error handler.
     *
     * @param {Error} error
     */
    errorHandler(error) {
        <?php if (LogLevel::isDebugMode()): ?>
        console.warn("Resurs Bank, Cache Management Widget", error);
        <?php endif; ?>

        this.onError(error.message || '<?= Translator::translate(phraseId: 'cache-clear-error') ?>');

        if (this.fetching) {
            this.toggleFetch(false);
        }
    }

    /**
     * Events performed when cache clear succeeds.
     * Override this method to handle success in your implementation.
     *
     * @param {any} data
     */
    onSuccess(data) {
        alert('<?= Translator::translate(phraseId: 'cache-cleared') ?>');
    }

    /**
     * Events performed when cache clear fails.
     * Override this method to handle errors in your implementation.
     *
     * @param {string} message
     */
    onError(message) {
        alert(message);
    }

    /**
     * Events performed when AJAX request has completed.
     * Override this method to add custom completion logic.
     */
    onComplete() {
        // Placeholder.
    }

    /**
     * Events performed when toggling.
     * Override this method to add custom toggle logic.
     *
     * @param {boolean} state
     */
    onToggle(state) {
        // Placeholder.
    }
}

document.addEventListener(
    'DOMContentLoaded',
    function () {
        new Resursbank_CacheManagement().setupEventListeners();
    }
);

