<?php

/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var PaymentInformation $this */
/** @psalm-scope-this PaymentInformation */

use Resursbank\Ecom\Lib\Locale\Translator;
use Resursbank\Ecom\Module\Payment\Widget\PaymentInformation;

$thStyle = 'font-size:1.3em; text-align:left; padding:0.2em 0.4em;';

?>

<div class="rb-pi" style="font-family:'ResursSans-Regular', Arial, sans-serif;">
    <table style="color: #fff; border-collapse:collapse;">
        <tr style="<?= $this->getTrStyle() ?>">
            <th style="<?= $thStyle ?>">
                <span><?= Translator::translate(phraseId: 'payment') ?></span>
                <span class="rb-pi-logo"><?= $this->logo ?></span>
            </th>
            <?php // Magento will strip colspan attribute. ?>
            <th></th>
        </tr
        </tr>
        <?= $this->getTrEl(title: 'payment-id', content: $this->getFormattedAmount($this->getAuthorizedAmount())) ?>
        <?= $this->getTrEl(title: 'authorized-amount', content: $this->getFormattedAmount($this->getAuthorizedAmount())) ?>
        <?= $this->getTrEl(title: 'captured-amount', content: $this->getFormattedAmount($this->getCapturedAmount())) ?>
        <?= $this->getTrEl(title: 'refunded-amount', content: $this->getFormattedAmount($this->getRefundedAmount())) ?>
        <?= $this->getTrEl(title: 'cancelled-amount', content: $this->getFormattedAmount($this->getCancelledAmount())) ?>
        <?= $this->getTrEl(title: 'status', content: $this->getStatus()) ?>
        <?= $this->getTrEl(title: 'payment-method', content: $this->getPaymentMethodName()) ?>
        <tr style="<?= $this->getTrStyle() ?>">
            <th style="<?= $thStyle ?>"><?= Translator::translate(phraseId: 'customer') ?></th>
            <?php // Magento will strip colspan attribute. ?>
            <th></th>
        </tr>
        <?= $this->getTrEl(title: 'name', content: $this->getCustomerName()) ?>
        <?php if ($this->hasAddress()): ?>
            <?= $this->getTrEl(title: 'address', content: $this->getAddressContent()) ?>
        <?php endif; ?>
        <?= $this->getTrEl(title: 'telephone', content: $this->getTelephone()) ?>
        <?= $this->getTrEl(title: 'email', content: $this->getEmail()) ?>
    </table>
</div>
