<?php

/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var PaymentInformation $this */
/** @psalm-scope-this PaymentInformation */

use Resursbank\Ecom\Lib\Locale\Translator;
use Resursbank\Ecom\Module\Payment\Widget\PaymentInformation;

?>

<div class="rb-pi">
  <table>
    <tr>
      <th colspan="2" class="rb-pi-logo-bg">
        <span><?= Translator::translate(phraseId: 'payment') ?></span>
        <span class="rb-pi-logo"><?= $this->logo ?></span>
      </th>
    </tr>
    <tr>
      <td class="rb-pi-row-header"><?= $this->getPaymentIdLabel() ?></td>
      <td><?= $this->paymentId ?></td>
    </tr>
    <tr>
      <td class="rb-pi-row-header"><?= Translator::translate(
	phraseId: 'authorized-amount'
) ?></td>
      <td><?= $this->getFormattedAmount(
	amount: $this->getAuthorizedAmount()
) ?></td>
    </tr>
    <tr>
      <td class="rb-pi-row-header"><?= Translator::translate(
	phraseId: 'captured-amount'
) ?></td>
      <td><?= $this->getFormattedAmount(
	amount: $this->getCapturedAmount()
) ?></td>
    </tr>
    <tr>
      <td class="rb-pi-row-header"><?= Translator::translate(
	phraseId: 'refunded-amount'
) ?></td>
      <td><?= $this->getFormattedAmount(
	amount: $this->getRefundedAmount()
) ?></td>
    </tr>
    <tr>
      <td class="rb-pi-row-header"><?= Translator::translate(
	phraseId: 'cancelled-amount'
) ?></td>
      <td><?= $this->getFormattedAmount(
	amount: $this->getCancelledAmount()
) ?></td>
    </tr>
    <tr>
      <td class="rb-pi-row-header"><?= Translator::translate(
	phraseId: 'status'
) ?></td>
      <td><?= $this->getStatus() ?></td>
    </tr>
    <tr>
      <td class="rb-pi-row-header"><?= Translator::translate(
	phraseId: 'payment-method'
) ?></td>
      <td><?= $this->getPaymentMethodName() ?></td>
    </tr>
    <tr>
      <th colspan="2"><?= Translator::translate(phraseId: 'customer') ?></th>
    </tr>
    <tr>
      <td class="rb-pi-row-header"><?= Translator::translate(
	phraseId: 'name'
) ?></td>
      <td><?= $this->getCustomerName() ?></td>
    </tr>
      <?php

if ($this->hasAddress()) : ?>
        <tr>
          <td class="rb-pi-row-header"><?= Translator::translate(
	phraseId: 'address'
) ?></td>
          <td>
              <?= $this->getAddressRow1() ?>
            <br />
              <?php

if ($this->getAddressRow2() !== '') : ?>
                    <?= $this->getAddressRow2() ?>
                <br />
              <?php endif; ?>
              <?= $this->getCity() ?>
            <br />
            <span>
              <?= $this->getCountryCode() ?>
                <?php

if ($this->getCountryCode() !== '') :
                    ?> - <?php
                endif; ?>
                <?= $this->getPostalCode() ?>
          </span>
          </td>
        </tr>
      <?php endif; ?>
    <tr>
      <td class="rb-pi-row-header"><?= Translator::translate(
	phraseId: 'telephone'
) ?></td>
      <td><?= $this->getTelephone() ?></td>
    </tr>
    <tr>
      <td class="rb-pi-row-header"><?= Translator::translate(
	phraseId: 'email'
) ?></td>
      <td><?= $this->getEmail() ?></td>
    </tr>
  </table>
</div>
