#!/bin/sh -eu

if [ ! -d .git/hooks ]; then
  echo "Error: Please run this script from the root of the repository."
  exit 1;
fi

# Resolve PHP cmd.
dockerCmd=""
phpService=""
phpCmd=""

read -p "Running PHP in Docker (y/n)?" localPhp
case "$localPhp" in
  y|Y ) read -p "Enter name of docker compose command (eg. docker compose or docker-compose): " dockerCmd; read -p "Enter name of php server (eg. php or phpfpm): " phpService; phpCmd="${dockerCmd} exec -T ${phpService}";;
  n|N ) read -p "Enter name of/path to php binary (eg. php): " php;;
  * ) echo "Invalid response."; exit 1;;
esac

read -p "Enter path to website root directory within PHP container (no trailing slash): " dir

HOOK_FILE=".git/hooks/pre-commit"

if [ -f $HOOK_FILE ]; then
  rm -f $HOOK_FILE
fi

touch $HOOK_FILE
chmod +x $HOOK_FILE

cat <<EOT >> $HOOK_FILE
#!/bin/sh -eu

PURPLE='\e[0;32m'
BLUE='\e[1;34m'
NC='\e[0m'

echo ""
echo "\${PURPLE}Running tests.\${NC}"
echo ""
echo ""
echo "=========================================================="
echo ""
echo "\${BLUE}Executing Psalm tests.\${NC}"
echo ""
echo ""
$phpCmd $dir/vendor/bin/psalm -c $dir/qa/psalm/psalm.xml --show-info=true
echo ""
echo "=========================================================="
echo ""
echo "\${BLUE}Executing PHPMD tests on source files.\${NC}"
echo ""
echo ""
$phpCmd $dir/vendor/bin/phpmd $dir/src text $dir/qa/phpmd/src.xml
echo ""
echo "=========================================================="
echo ""
echo "\${BLUE}Executing PHPMD tests on test files.\${NC}"
echo ""
echo ""
$phpCmd $dir/vendor/bin/phpmd $dir/tests text $dir/qa/phpmd/tests.xml
echo ""
echo "=========================================================="
echo ""
echo "\${BLUE}Executing PHP CBF for source files.\${NC}"
echo ""
echo ""
$phpCmd $dir/vendor/bin/phpcbf --standard=PSR12 $dir/src
echo ""
echo "=========================================================="
echo ""
echo "\${BLUE}Executing PHP CBF for test files.\${NC}"
echo ""
echo ""
$phpCmd $dir/vendor/bin/phpcbf --standard=PSR12 $dir/tests
echo ""
echo "=========================================================="
echo ""
echo "\${BLUE}Executing PHPCS for source files.\${NC}"
echo ""
echo ""
$phpCmd $dir/vendor/bin/phpcs --standard=PSR12 $dir/src
echo ""
echo "=========================================================="
echo ""
echo "\${BLUE}Executing PHPCS for test files.\${NC}"
echo ""
echo ""
$phpCmd $dir/vendor/bin/phpcs --standard=PSR12 $dir/tests
echo ""
echo "=========================================================="
echo ""
echo "\${BLUE}Executing PHPStan for source files.\${NC}"
echo ""
echo ""
$phpCmd $dir/vendor/bin/phpstan analyse $dir/src
echo ""
echo "=========================================================="
echo ""
echo "\${BLUE}Executing PHPStan for test files.\${NC}"
echo ""
echo ""
$phpCmd $dir/vendor/bin/phpstan analyse $dir/tests
echo ""
echo "=========================================================="
EOT

if [ ! -d ./qa/psalm/cache ]; then
  mkdir ./qa/psalm/cache
fi

echo OK
exit 0
