#!/bin/sh -e

if [ ! -d .git/hooks ]; then
  echo "Error: Please run this script from the root of the repository."
  exit 1;
fi

read -p "Enter name of docker-compose php service: " service
read -p "Enter path to website root directory within PHP container (no trailing slash): " dir

HOOK_FILE=".git/hooks/pre-commit"

if [ -f $HOOK_FILE ]; then
  rm -f $HOOK_FILE
fi

touch $HOOK_FILE
chmod +x $HOOK_FILE

cat <<EOT >> $HOOK_FILE
#!/bin/sh -e

# @todo Make sure PHP is available, otherwise let us know so the commit does not fail silently.

PURPLE='\035[0;32m'
BLUE='\033[1;34m'
NC='\033[0m'

echo "${PURPLE}Running tests.${NC}"

echo "=========================================================="
echo ""
echo ""
echo "${BLUE}Executing Psalm tests.${NC}"
echo ""
echo ""
docker-compose exec -T $service psalm -c $dir/qa/psalm/psalm.xml --show-info=true
echo ""
echo ""
echo "=========================================================="
echo ""
echo ""
echo "${BLUE}Executing PHPMD tests on source files.${NC}"
echo ""
echo ""
docker-compose exec -T $service phpmd $dir/src text $dir/qa/phpmd/src.xml
echo ""
echo ""
echo "=========================================================="
echo ""
echo ""
echo "${BLUE}Executing PHPMD tests on test files.${NC}"
echo ""
echo ""
docker-compose exec -T $service phpmd $dir/tests text $dir/qa/phpmd/tests.xml
echo ""
echo ""
echo "=========================================================="
echo ""
echo ""
echo "${BLUE}Executing PHP CBF for source files.${NC}"
echo ""
echo ""
docker-compose exec -T $service phpcbf --standard=PSR12 $dir/src
echo ""
echo ""
echo "=========================================================="
echo ""
echo ""
echo "${BLUE}Executing PHP CBF for test files.${NC}"
echo ""
echo ""
docker-compose exec -T $service phpcbf --standard=PSR12 $dir/tests
echo ""
echo ""
echo "=========================================================="
echo ""
echo ""
echo "${BLUE}Executing PHPCS for source files.${NC}"
echo ""
echo ""
docker-compose exec -T $service phpcs --standard=PSR12 $dir/src
echo ""
echo ""
echo "=========================================================="
echo ""
echo ""
echo "${BLUE}Executing PHPCS for test files.${NC}"
echo ""
echo ""
docker-compose exec -T $service phpcs --standard=PSR12 $dir/tests
echo ""
echo ""
echo "=========================================================="
echo ""
echo ""
echo "${BLUE}Executing PHPStan for source files.${NC}"
echo ""
echo ""
docker-compose exec -T $service phpstan analyse $dir/src
echo ""
echo ""
echo "=========================================================="
echo ""
echo ""
echo "${BLUE}Executing PHPStan for test files.${NC}"
echo ""
echo ""
docker-compose exec -T $service phpstan analyse $dir/tests
echo ""
echo ""
echo "=========================================================="
EOT

if [ ! -d ./qa/psalm/cache ]; then
  mkdir ./qa/psalm/cache
fi

echo OK
exit 0
